# Generated by Django 5.0.6 on 2024-06-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfinityStones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=250)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
